name: test
on:
  pull_request:
    paths-ignore:
      - .github/dependabot.yml
      - CHANGELOG.md
      - LICENSE
      - README.md
  push:
    paths-ignore:
      - .github/dependabot.yml
      - CHANGELOG.md
      - LICENSE
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"
      - uses: golangci/golangci-lint-action@v3
      - run: make gen && git diff --exit-code
      - name: Start services
        run: |
          for i in {1..60}; do docker compose up -d && break; sleep 1; done
          for i in {1..60}; do pg_isready -U postgres -h 127.0.0.1 -p 15432 && break; sleep 1; done
      - run: make redash-setup
      - run: make vet
      - run: make testacc
